### ISSUE TITLE
allow players to add their smashdata.gg link in their profile

### ISSUE THREAD

**Issue by teluoborg** [Yoshi20/FranceSmash#4]
I guess it's not possible to extract the data from the page (like winrate and stuff) and display it on the site but at least it'd be cool to let players add the link to show their tournaments results

**Comment by Yoshi20** [comment]
Template:
https://smashbrothers.at/en/register/
https://help.smash.gg/en/articles/4855957-discriminators-on-smash-gg

**Comment by teluoborg** [comment]
nice
